#
# Build stage
#
FROM maven:latest AS build
COPY . .
RUN mvn clean package -DskipTests

#
# Package stage
#
FROM openjdk:17-jdk-slim
COPY --from=build /target/VendorValley-0.0.1-SNAPSHOT.jar VendorValley.jar
# ENV PORT=8080
EXPOSE 8080
ENTRYPOINT ["java","-jar","VendorValley.jar"]